config/routes.rb
Obxpi::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "user_info", to: "users#info"
  get "poison_pet/:id", to: "users#poison_pet", as: :poison_pet
  get "generate_pet/:id", to: "users#generate_pet", as: :generate_pet
  resources :users do
    resource :page
  end
  
  resources :forums do
    resources :topics do
      get "vote", on: :member
      resources :posts do
        get "vote", on: :member
      end
    end
  end
  
  resources :mentions
  
  resources :shouts
  
  post "shout", to: "misc#shout", as: :misc_shout
  
  get "admin", to: "admin#index"
  get "admin/:user_id/make", to: "admin#make", as: :make_admin
  get "admin/:user_id/remove", to: "admin#remove", as: :remove_admin
  get "admin/edit_user/:user_id", to: "admin#edit_user", as: :edit_user_admin
  patch "admin/update_user/:user_id", to: "admin#update_user", as: :update_user_admin
  
  get "u/:user_name", to: "pages#show", as: :u_page
  
  get "online_users", to: "home#online_users", as: :online_users
  get "activity_log", to: "home#activity_log"
  get "stream", to: "home#stream"
  
  root to: "shouts#index"
  
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :topics
  has_many :posts, through: :topics
  
  def last_activity
    post = self.posts.order(updated_at: :desc).first
    topic = self.topics.order(updated_at: :desc).first
    
    return post unless topic
    return topic unless post
    
    if post.updated_at > topic.updated_at
      post
    else
      topic
    end
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_user?, only: [:create]
  
  def index
    @forums = Forum.all
  end
  
  def show
    @forum = Forum.find(forum_id)
    @topics = @forum.topics.order(created_at: :desc)
  end
  
  def create
    forum = Forum.new(forum_params)
    forum.save
    redirect_to admin_path
  end
  
  private
  
  def forum_params
    params.require(:forum).permit(:name)
  end
  
  def forum_id
    params[:id]
  end
end

app/views/forums/index.html.erb
<section id="forum" class="with_stream">
  <ul class="titles">
    <li class="forum_title">Forum</li>
    <li class="topic_title">Topics</li>
    <li class="post_title">Posts</li>
    <li class="last_activity_title">Last Activity</li>
  </ul>
  <% @forums.each do |forum| %>
    <ul class="forum_row">
      <li class="forum_name"><%= link_to forum.name, forum_path(forum) %></li>
      <li class="forum_topic"><%= forum.topics.count %></li>
      <li class="forum_post_count"><%= forum.posts.count %></li>
      <li class="forum_last_activity">      
        <% if forum.last_activity %>
          <% if forum.last_activity.is_a?(Topic) %>
            <%= link_to forum.last_activity.name, forum_topic_path(forum, forum.last_activity) %>
          <% else %>
           <%= link_to forum.last_activity.topic.name, forum_topic_path(forum, forum.last_activity.topic) %>
          <% end %>
          by <%= format_and_link_user(forum.last_activity.user) %> 
          <%= time_ago_in_words forum.last_activity.updated_at %> ago
          <% else %>
          None
        <% end %>
      </li>
    </ul>
  <% end %>
</section>
<%= render partial: "shared/recent_activity" %>

app/views/forums/show.html.erb
  <table id="forum">
    <tr>
      <th>Votes</th>
      <th> </th>
      <th>Topic</th>
      <th>Created By</th>
      <th>Last Post</th>
    <% @topics.each do |topic| %>
    <tr class="<%= cycle(" selected", "") %>">
      <td><%= topic.votes.count %></td>
      <td>
        <%= vote_link_for_topic(topic) %>
      </td>
      <td><%= link_to topic.name, forum_topic_path(@forum, topic) %></td>
      <td>
        <%= format_and_link_user(topic.user) %>
        <%= time_ago_in_words topic.created_at %> ago
      </td>
      <td>
        <% if topic.last_post %>
          by <%= format_and_link_user(topic.last_post.user) %> 
          <%= time_ago_in_words topic.last_post.updated_at %> ago
        <% else%>
          None
        <% end %>
      </td>

    </tr>
    <% end %>
  <table>

  <% if user_signed_in? %>
    <h2>New Topic</h2>

    <div>
    <%= form_for Topic.new, url: forum_topics_path(@forum) do |f| %>
      <div>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.text_area :body %>
      </div>
      <%= f.submit %>
    <% end %>
    </div>
  <% end %>
  