config/routes.rb
Obxpi::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "user_info", to: "users#info"
  get "poison_pet/:id", to: "users#poison_pet", as: :poison_pet
  get "generate_pet/:id", to: "users#generate_pet", as: :generate_pet
  resources :users do
    resource :page
  end
  
  resources :forums do
    resources :topics do
      get "vote", on: :member
      resources :posts do
        get "vote", on: :member
      end
    end
  end
  
  resources :mentions
  
  resources :shouts
  
  post "shout", to: "misc#shout", as: :misc_shout
  
  get "admin", to: "admin#index"
  get "admin/:user_id/make", to: "admin#make", as: :make_admin
  get "admin/:user_id/remove", to: "admin#remove", as: :remove_admin
  get "admin/edit_user/:user_id", to: "admin#edit_user", as: :edit_user_admin
  patch "admin/update_user/:user_id", to: "admin#update_user", as: :update_user_admin
  
  get "u/:user_name", to: "pages#show", as: :u_page
  
  get "online_users", to: "home#online_users", as: :online_users
  get "activity_log", to: "home#activity_log"
  get "stream", to: "home#stream"
  
  root to: "shouts#index"
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates_presence_of :name, :body
  
  belongs_to :forum
  belongs_to :user
  
  has_many :posts
  has_many :mentions, as: :mentionable
  has_many :votes
  
  def last_post
    posts.order(updated_at: :desc).first
  end
  
  def user_has_voted?(user)
    self.votes.where(user_id: user.id).count > 0
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_user_has_edits, only: [:edit, :update]
  
  def create
    forum = Forum.find(forum_id)
    topic = forum.topics.new(topic_params.merge(user: current_user))
    if topic.save
      Mention.generate(topic)
      ActivityLog.log('topic', topic.id, current_user)
      current_user.give_edits(1)
      flash[:notice] = "Topic created! Booyah."
    else
      flash[:notice] = "That topic could not be created. Try again?"
    end
    redirect_to forum_path(forum)
  end
  
  def show
    @topic = Forum.find(forum_id).topics.find(topic_id)
    @posts = @topic.posts.order(created_at: :desc)
  end
  
  def edit
    @topic = Topic.find(topic_id)
  end
  
  def update
    topic = Topic.find(topic_id)
    if topic.update_attributes(topic_params)
      Mention.generate(topic)
      current_user.take_edit!
    end
    redirect_to forum_topic_path(topic.forum, topic)
  end
  
  def vote
    topic = Topic.find(topic_id)
    if topic.user_has_voted?(current_user)
      flash[:notice] = "You already voted!"
    else
      if current_user.edits >= 1
        current_user.take_edit!
        topic.user.give_edits(1)
        flash[:notice] = "Your vote has been counted."
        Vote.create(user: current_user, topic: topic)
      else
        flash[:notice] = "You need at least 1 edit to vote!"
      end
    end
    redirect_to return_to_location
  end
  
  private
  
  def topic_params
    params.require(:topic).permit(:name, :body)
  end
  
  def forum_id
    params[:forum_id]
  end
  
  def topic_id
    params[:id]
  end
end

app/views/topics/edit.html.erb
<h2>Edit Topic</h2>

<%= form_for @topic, url: forum_topic_path(@topic.forum, @topic) do |f| %>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/topics/show.html.erb
<div class="bread">
  <%= link_to(@topic.forum.name, forum_path(@topic.forum)) %> / <%= @topic.name %>
</div>

<br />

<div class="op_container">
  <h2><%= @topic.name %></h2>
  <p>
    <%= format_model_body(@topic, kramdown_format: true) %>
  </p>
  <div class="op_info">
    <div class="avatar_wrap">
      <div class="avatar">
        <%= image_tag @topic.user.avatar.url(:thumb) %> 
      </div>
    </div>
    <%= format_and_link_user @topic.user %>
    <%= time_ago_in_words @topic.created_at %> ago
    <%= vote_link_for_topic(@topic) %>
    <%= link_to "Edit", edit_forum_topic_path(@topic.forum, @topic) if user_has_edits? %>
  </div>
</div>

<div id="comments" class="comment-section">
  <% if user_signed_in? %>
    <%= form_for [@topic.forum, @topic, Post.new] do |f| %>
      <%= f.text_field :body, class: "inline-comment-input", autocomplete: "off" %>
      <%= f.submit "Reply", class: "inline-comment-submit" %>
    <% end %>
  <% end %>
  
  <% @posts.each do |post| %>
  <div class="comment<%= cycle(" selected", "") %>">
    <div class="avatar_wrap">
      <div class="avatar">
        <%= image_tag post.user.avatar.url(:thumb) %> 
      </div>
    </div>
    <div>
      <%= format_and_link_user post.user %>
      <%= time_ago_in_words post.created_at %> ago
      <%= vote_link_for_post(post) %>
      <%= link_to "Edit", edit_forum_topic_post_path(@topic.forum, @topic, post) if user_has_edits? %>
    </div>
    <p>
      <%= format_model_body(post) %>
    </p>
  </div>
  <% end %>
</div>