config/routes.rb
Obxpi::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "user_info", to: "users#info"
  get "poison_pet/:id", to: "users#poison_pet", as: :poison_pet
  get "generate_pet/:id", to: "users#generate_pet", as: :generate_pet
  resources :users do
    resource :page
  end
  
  resources :forums do
    resources :topics do
      get "vote", on: :member
      resources :posts do
        get "vote", on: :member
      end
    end
  end
  
  resources :mentions
  
  resources :shouts
  
  post "shout", to: "misc#shout", as: :misc_shout
  
  get "admin", to: "admin#index"
  get "admin/:user_id/make", to: "admin#make", as: :make_admin
  get "admin/:user_id/remove", to: "admin#remove", as: :remove_admin
  get "admin/edit_user/:user_id", to: "admin#edit_user", as: :edit_user_admin
  patch "admin/update_user/:user_id", to: "admin#update_user", as: :update_user_admin
  
  get "u/:user_name", to: "pages#show", as: :u_page
  
  get "online_users", to: "home#online_users", as: :online_users
  get "activity_log", to: "home#activity_log"
  get "stream", to: "home#stream"
  
  root to: "shouts#index"
  
end

app/views/admin/index.html.erb
<div>
  <h2>Forum</h2>

  <div>
    <% @forums.each do |forum| %>
      <p><%= forum.name %></p>
    <% end %>
  </div>

  <div>
  <%= form_for Forum.new do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
  </div>
</div>

<br />
<br />


<div>
  <h2>Users</h2>
  
  <% @users.each do |user| %>
  <p>
    <%= user.name %> 
    <%= link_to "Make Admin", make_admin_path(user) unless user.admin? %>
    <%= link_to "Remove Admin", remove_admin_path(user) if user.admin? %>
  </p>
  <% end %>
</div>